config/routes.rb
Rails.application.routes.draw do
  root 'import#data'
  get 'import' => 'import#form', as: 'import'
  post 'import' => 'import#import'
  get 'export' => 'tickets#index', constraints: lambda { |req| req.format == :csv }

end

app/controllers/import_controller.rb
class ImportController < ApplicationController
  def data
  end

  def form
  end

  def import
    require 'tempfile'
    file = params[:file]
    recodedFile = Tempfile.new('recodedImport')
    File.open(recodedFile.path, 'w') do |out|
      out << File.open(file.path).read.encode("UTF-8", :invalid=>:replace, :replace=>"?")
    end 
    CSV.foreach(recodedFile.path, :headers => true, col_sep: ";") do |row|
      hashRow = row.to_hash
      if !Ticket.find_by ref: hashRow['Numero billet']
        s = Spectacle.create_with(name: hashRow['Spectacle']).find_or_create_by(cle: hashRow['Cle spectacle'])
        repArgs = {
          name: hashRow['Representation'],
          startDate: hashRow['Date representation'],
          startTime: hashRow['Heure representation'],
          endDate: hashRow['Date fin representation'],
          endTime: hashRow['Heure fin representation'],
          spectacle: s
        }
        r = Representation.create_with(repArgs).find_or_create_by(cle: hashRow['Cle representation'])
        dict = {"F"=>"female", "M"=>"male"}
        s = dict.include? hashRow['Sexe'] ? dict[hashRow['Sexe']] : ""
        clientArgs = {
          kind: hashRow['Type de client'],
          name: hashRow['Nom'],
          firstname: hashRow['Prenom'],
          adresse: hashRow['Adresse'],
          codePostal: hashRow['Code postal'],
          country: hashRow['Pays'],
          age: hashRow['Age'],
          sexe: s
        }
        c = Client.create_with(clientArgs).find_or_create_by(email: hashRow['Email'])
        ticketArgs = {
          ref: hashRow['Numero billet'],
          command: hashRow['Commande'],
          reservation: hashRow['Reservation'],
          resaDate: hashRow['Date reservation'],
          resaTime: hashRow['Heur reservation'],
          price: hashRow['Prix'],
          accessDate: hashRow['Date acces'],
          accessTime: hashRow['Heure acces'],
          tarif: hashRow['Tarif'],
          kind: hashRow['Type de produit'],
          serie: hashRow['Serie'],
          floor: hashRow['Etage'],
          sellPoint: hashRow['Filiere de vente'],
          representation: r,
          client: c
        }
        t = Ticket.new ticketArgs
        t.save
      end
    end
    redirect_to root_path, notice: "Success!"
  end
end

app/helpers/import_helper.rb
module ImportHelper
end

app/views/import/data.html.erb
<div class="container"><div class="row">
<%= flash[:notice] %>

<h2>Data</h2>
<div class="btn-group" role="group" aria-label="...">
  <%= link_to 'Import', import_path, class: "btn btn-default" %>
  <%= link_to "Export", export_path(format: "csv"), class: "btn btn-default" %>
</div>

<div>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#count" aria-controls="count" role="tab" data-toggle="tab">Counts</a></li>
    <li role="presentation"><a href="#age" aria-controls="age" role="tab" data-toggle="tab">Average age</a></li>
    <li role="presentation"><a href="#spectacle" aria-controls="spectacle" role="tab" data-toggle="tab">By spectacle</a></li>
    <li role="presentation"><a href="#client" aria-controls="client" role="tab" data-toggle="tab">By client</a></li>
    <li role="presentation"><a href="#cart" aria-controls="cart" role="tab" data-toggle="tab">By cart</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="count">
      <table class="table table-striped">
        <tbody>
            <tr>
              <td>Ticket</td>
              <td><%= Ticket.count %></td>
            </tr>
            <tr>
              <td>Spectacle</td>
              <td><%= Spectacle.count %></td>
            </tr>
            <tr>
              <td>Representation</td>
              <td><%= Representation.count %></td>
            </tr>
            <tr>
              <td>Client</td>
              <td><%= Client.count %></td>
            </tr>
        </tbody>
      </table>
    </div>
    <div role="tabpanel" class="tab-pane" id="age">
      <%= Client.average(:age) %>
    </div>
    <div role="tabpanel" class="tab-pane" id="spectacle">
      <table class="table table-striped">
        <thead>
            <th>Name</th>
            <th>Average ticket price</th>
            <th>Representations</th>
            <th>Tickets</th>
        </thead>
        <tbody>
          <% Spectacle.all.each do |s| %>
            <tr>
              <td><%= s.name %></td>
              <td><%= s.tickets.average(:price) %></td>
              <td><%= s.representations.count %></td>
              <td><%= s.tickets.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div role="tabpanel" class="tab-pane" id="client">
      <table class="table table-striped">
        <thead>
            <th>Name</th>
            <th>Average price</th>
            <th>Tickets</th>
        </thead>
        <tbody>
          <% Client.all.each do |c| %>
            <tr>
              <td><%= c.firstname + " " + c.name %></td>
              <td><%= c.tickets.average(:price) %></td>
              <td><%= c.tickets.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div role="tabpanel" class="tab-pane" id="cart">
      <% carts = Ticket.group(:reservation).average(:price) %>
      <p>Average cart price : <%= carts.sum(&:last)/carts.size %></p>
      <table class="table table-striped">
        <thead>
            <th>Reservation number</th>
            <th>Average ticket price</th>
        </thead>
        <tbody>
          <% carts.each do |cart| %>
            <tr>
              <td><%= cart.first %></td>
              <td><%= cart.last %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

</div></div>

app/views/import/form.html.erb
<div class="container"><div class="row">

<%= flash[:notice] %>

<h2>Import data</h2>
<%= form_tag import_path, multipart: true do %>
  <div class="form-group">
    <%= file_field_tag :file %>
  </div>
  <%= submit_tag "Import", class: "btn btn-default" %>
  <%= link_to "Cancel", root_path, class: "btn btn-default" %>
<% end %>

</div></div>